const CubesConstant = [
  { index: 0, isOpen: false, isSafe: true, isTreasure: false },
  { index: 1, isOpen: false, isSafe: true, isTreasure: false },
  { index: 2, isOpen: false, isSafe: true, isTreasure: false },
  { index: 3, isOpen: false, isSafe: true, isTreasure: false },
  { index: 4, isOpen: false, isSafe: true, isTreasure: false },
  { index: 5, isOpen: false, isSafe: true, isTreasure: false },
  { index: 6, isOpen: false, isSafe: true, isTreasure: false },
  { index: 7, isOpen: false, isSafe: true, isTreasure: false },
  { index: 8, isOpen: false, isSafe: true, isTreasure: false },
  { index: 9, isOpen: false, isSafe: true, isTreasure: false },
  { index: 10, isOpen: false, isSafe: true, isTreasure: false },
  { index: 11, isOpen: false, isSafe: true, isTreasure: false },
  { index: 12, isOpen: false, isSafe: true, isTreasure: false },
  { index: 13, isOpen: false, isSafe: true, isTreasure: false },
  { index: 14, isOpen: false, isSafe: true, isTreasure: false },
  { index: 15, isOpen: false, isSafe: true, isTreasure: false },
  { index: 16, isOpen: false, isSafe: true, isTreasure: false },
  { index: 17, isOpen: false, isSafe: true, isTreasure: false },
  { index: 18, isOpen: false, isSafe: true, isTreasure: false },
  { index: 19, isOpen: false, isSafe: true, isTreasure: false },
  { index: 20, isOpen: false, isSafe: true, isTreasure: false },
  { index: 21, isOpen: false, isSafe: true, isTreasure: false },
  { index: 22, isOpen: false, isSafe: true, isTreasure: false },
  { index: 23, isOpen: false, isSafe: true, isTreasure: false },
  { index: 24, isOpen: false, isSafe: true, isTreasure: false },
];
export default CubesConstant;
